// Protocol
export { clientMessageSchema, serverMessageSchema } from './protocol/envelope';
export type { ClientMessage, ConnectionState, ServerMessage } from './protocol/envelope';
export { ErrorCodeSchema, ProtocolErrorSchema } from './protocol/error';
export type { ErrorCode, ProtocolError } from './protocol/error';
export { err, ok, resultSchema } from './protocol/result';
export type { Result } from './protocol/result';
export { PROTOCOL_VERSION } from './protocol/version';
export type { ProtocolVersion } from './protocol/version';
export {
    AGENT_ACK,
    AGENT_AUTH_EVENTS,
    AGENT_COLLECT,
    AGENT_CONFIG,
    AGENT_DESTROY,
    AGENT_DESTROYED,
    AGENT_ERROR,
    AGENT_FILES_ANALYZE,
    AGENT_FILES_CHUNK,
    AGENT_FILES_DOWNLOAD,
    AGENT_FILES_LIST,
    AGENT_FILES_LISTING,
    AGENT_FILES_MATCHES,
    AGENT_FILES_MUTATE,
    AGENT_FILES_OP_RESULT,
    AGENT_FILES_SEARCH,
    AGENT_FILES_UPLOAD,
    AGENT_FILES_USAGE,
    AGENT_HELLO,
    AGENT_INTEGRITY,
    AGENT_LIFECYCLE,
    AGENT_LOG_LINES,
    AGENT_LOG_QUERY,
    AGENT_LOG_SOURCES,
    AGENT_LOG_SOURCES_RESULT,
    AGENT_METRICS_BATCH,
    AGENT_PKG_DONE,
    AGENT_PKG_LIST,
    AGENT_PKG_LIST_RESULT,
    AGENT_PKG_PROGRESS,
    AGENT_PKG_UPGRADE,
    AGENT_POWER,
    AGENT_POWER_RESULT,
    AGENT_REPORT,
    AGENT_SCAN,
    AGENT_SERVICE,
    AGENT_SERVICE_RESULT,
    AGENT_SYNC_ACK,
    AGENT_SYNC_APPLY_CHUNK,
    AGENT_SYNC_CHANGED,
    AGENT_SYNC_CHUNK,
    AGENT_SYNC_CONFIG,
    AGENT_SYNC_DELETE,
    AGENT_SYNC_INDEX,
    AGENT_SYNC_OP_RESULT,
    AGENT_SYNC_PUSH,
    AGENT_SYNC_SCAN,
    AGENT_TERM_CLOSE,
    AGENT_TERM_EXIT,
    AGENT_TERM_INPUT,
    AGENT_TERM_OPEN,
    AGENT_TERM_OUTPUT,
    AGENT_TERM_RESIZE,
    AGENT_UPDATE,
    AGENT_UPDATED,
    agentClientMessageSchema,
    agentConfigPayloadSchema,
    agentDestroyedMessagePayloadSchema,
    agentFilesAnalyzePayloadSchema,
    agentFilesChunkPayloadSchema,
    agentFilesDownloadPayloadSchema,
    agentFilesListPayloadSchema,
    agentFilesListingPayloadSchema,
    agentFilesMatchesPayloadSchema,
    agentFilesMutatePayloadSchema,
    agentFilesOpResultPayloadSchema,
    agentFilesSearchPayloadSchema,
    agentFilesUploadPayloadSchema,
    agentFilesUsagePayloadSchema,
    agentLifecycleActionSchema,
    agentLifecyclePayloadSchema,
    agentLogLinesPayloadSchema,
    agentLogQueryPayloadSchema,
    agentLogSourcesResultPayloadSchema,
    agentPkgDonePayloadSchema,
    agentPkgListResultPayloadSchema,
    agentPkgProgressPayloadSchema,
    agentPkgUpgradePayloadSchema,
    agentPowerActionSchema,
    agentPowerPayloadSchema,
    agentPowerResultPayloadSchema,
    agentAuthEventsMessagePayloadSchema,
    agentIntegrityMessagePayloadSchema,
    agentReportMessagePayloadSchema,
    agentServerMessageSchema,
    agentServiceActionSchema,
    agentServicePayloadSchema,
    agentServiceResultPayloadSchema,
    agentSyncAckPayloadSchema,
    agentSyncApplyChunkPayloadSchema,
    agentSyncChangedPayloadSchema,
    agentSyncChunkPayloadSchema,
    agentSyncConfigPayloadSchema,
    agentSyncDeletePayloadSchema,
    agentSyncIndexPayloadSchema,
    agentSyncOpResultPayloadSchema,
    agentSyncPushPayloadSchema,
    agentSyncScanPayloadSchema,
    agentTermClosePayloadSchema,
    agentTermExitPayloadSchema,
    agentTermInputPayloadSchema,
    agentTermOpenPayloadSchema,
    agentTermOutputPayloadSchema,
    agentTermResizePayloadSchema,
    agentUpdatedMessagePayloadSchema,
    agentUpdatePayloadSchema,
    CLOUD_SYNC_CHUNK_EVENT,
    CLOUD_SYNC_PROGRESS_EVENT,
    CLOUD_SYNC_STATE_EVENT,
    cloudSyncChunkPushSchema,
    cloudSyncProgressPushSchema,
    cloudSyncStatePushSchema,
    DEVICE_FILES_CHUNK_EVENT,
    DEVICE_FILES_LISTING_EVENT,
    DEVICE_FILES_MATCHES_EVENT,
    DEVICE_FILES_OP_EVENT,
    DEVICE_FILES_USAGE_EVENT,
    DEVICE_LOG_LINES_EVENT,
    DEVICE_LOG_SOURCES_EVENT,
    DEVICE_POWER_EVENT,
    DEVICE_PRESENCE_EVENT,
    DEVICE_REPORT_EVENT,
    DEVICE_SERVICE_EVENT,
    DEVICE_TERM_EXIT_EVENT,
    DEVICE_TERM_OUTPUT_EVENT,
    deviceFilesChunkPushSchema,
    deviceFilesListingPushSchema,
    deviceFilesMatchesPushSchema,
    deviceFilesOpPushSchema,
    deviceFilesUsagePushSchema,
    deviceLogLinesPushSchema,
    deviceLogSourcesPushSchema,
    devicePowerPushSchema,
    devicePresenceSchema,
    deviceReportPushSchema,
    deviceServicePushSchema,
    deviceTermExitPushSchema,
    deviceTermOutputPushSchema,
    METRICS_PUSH_EVENT,
    metricsPushSchema,
    PACKAGE_DONE_EVENT,
    PACKAGE_LIST_EVENT,
    PACKAGE_PROGRESS_EVENT,
    PACKAGE_STARTED_EVENT,
    packageDonePushSchema,
    packageListPushSchema,
    packageProgressPushSchema,
    packageStartedPushSchema,
    syncIndexEntrySchema,
    syncShareAssignmentSchema
} from './protocol/agent';
export type {
    AgentClientMessage,
    AgentConfigPayload,
    AgentFilesAnalyzePayload,
    AgentFilesDownloadPayload,
    AgentFilesListPayload,
    AgentFilesMutatePayload,
    AgentFilesSearchPayload,
    AgentFilesUploadPayload,
    AgentLifecycleAction,
    AgentLifecyclePayload,
    AgentLogQueryPayload,
    AgentPkgUpgradePayload,
    AgentPowerAction,
    AgentPowerPayload,
    AgentServerMessage,
    AgentServiceAction,
    AgentServicePayload,
    AgentSyncApplyChunkPayload,
    AgentSyncConfigPayload,
    AgentSyncDeletePayload,
    AgentSyncPushPayload,
    AgentSyncScanPayload,
    AgentTermClosePayload,
    AgentTermInputPayload,
    AgentTermOpenPayload,
    AgentTermResizePayload,
    AgentUpdatePayload,
    CloudSyncChunkPush,
    CloudSyncProgressPush,
    CloudSyncStatePush,
    DeviceFilesChunkPush,
    DeviceFilesListingPush,
    DeviceFilesMatchesPush,
    DeviceFilesOpPush,
    DeviceFilesUsagePush,
    DeviceLogLinesPush,
    DeviceLogSourcesPush,
    DevicePowerPush,
    DevicePresence,
    DeviceReportPush,
    DeviceServicePush,
    DeviceTermExitPush,
    DeviceTermOutputPush,
    MetricsPush,
    PackageDonePush,
    PackageListPush,
    PackageProgressPush,
    PackageStartedPush,
    SyncIndexEntry,
    SyncShareAssignment
} from './protocol/agent';

// Domain
export {
    LOG_CATEGORIES,
    LOG_LEVEL_NAMES,
    LOG_LEVELS,
    logEntrySchema,
    logLevelName,
    logLevelNameSchema,
    logLevelValue,
    logSourceSchema
} from './domain/logs';
export type { LogCategory, LogEntry, LogLevelName, LogRow, LogSource } from './domain/logs';
export {
    DEVICE_LOG_LEVELS,
    DEVICE_LOG_PAGE_DEFAULT,
    DEVICE_LOG_PAGE_MAX,
    deviceLogFilterSchema,
    deviceLogLevelSchema,
    deviceLogLineSchema,
    deviceLogSourceKindSchema,
    deviceLogSourceSchema
} from './domain/deviceLogs';
export type {
    DeviceLogFilter,
    DeviceLogLevel,
    DeviceLogLine,
    DeviceLogSource,
    DeviceLogSourceKind
} from './domain/deviceLogs';
export {
    cloudSyncEventSchema,
    cloudSyncExclusionSchema,
    cloudSyncFileSchema,
    cloudSyncProgressSchema,
    cloudSyncShareDeviceSchema,
    cloudSyncShareSchema,
    cloudSyncShareStateSchema,
    cloudSyncShareStatsSchema,
    cloudSyncVersionSchema,
    sha256HexSchema,
    SYNC_CHUNK_MAX,
    SYNC_DEFAULT_IGNORED_NAMES,
    SYNC_INDEX_BATCH_MAX,
    SYNC_MTIME_SKEW_MS,
    SYNC_NAME_MAX,
    SYNC_PATTERN_MAX,
    SYNC_REL_PATH_MAX,
    SYNC_STORAGE_PATH_MAX,
    syncConflictPolicySchema,
    syncDirectionSchema,
    syncExclusionKindSchema,
    syncFileStateSchema,
    syncSessionStateSchema,
    syncShareStatusSchema,
    syncVersionReasonSchema,
    syncVersionSortSchema
} from './domain/cloudSync';
export type {
    CloudSyncEvent,
    CloudSyncExclusion,
    CloudSyncFile,
    CloudSyncProgress,
    CloudSyncShare,
    CloudSyncShareDevice,
    CloudSyncShareState,
    CloudSyncShareStats,
    CloudSyncVersion,
    SyncConflictPolicy,
    SyncDeviceFileRow,
    SyncDirection,
    SyncEventRow,
    SyncExclusionKind,
    SyncExclusionRow,
    SyncFileRow,
    SyncFileState,
    SyncSessionRow,
    SyncSessionState,
    SyncShareDeviceRow,
    SyncShareRow,
    SyncShareStatus,
    SyncVersionReason,
    SyncVersionRow,
    SyncVersionSort
} from './domain/cloudSync';
export {
    FILE_SEARCH_MAX,
    fileEntrySchema,
    fileKindSchema,
    fileListingSchema,
    fileMatchSchema,
    fileMutateOpSchema,
    fileSearchFieldSchema,
    fileSearchFilterSchema,
    fileUsageEntrySchema
} from './domain/deviceFiles';
export type {
    FileEntry,
    FileKind,
    FileListing,
    FileMatch,
    FileMutateOp,
    FileSearchField,
    FileSearchFilter,
    FileUsageEntry
} from './domain/deviceFiles';
export {
    passwordEntryMaskedSchema,
    passwordEntrySchema,
    passwordStatusSchema
} from './domain/password';
export type {
    PasswordEntry,
    PasswordEntryMasked,
    PasswordRow,
    PasswordStatus
} from './domain/password';
export {
    NOTE_BLOCK_TEXT_MAX_LENGTH,
    NOTE_FOLDER_MAX_LENGTH,
    NOTE_MAX_BLOCKS,
    NOTE_TITLE_MAX_LENGTH,
    noteBlockSchema,
    noteBulletBlockSchema,
    noteCheckBlockSchema,
    noteColorSchema,
    noteDividerBlockSchema,
    noteFolderSchema,
    noteHeadingBlockSchema,
    noteNumberBlockSchema,
    noteSchema,
    noteSummarySchema,
    noteTextBlockSchema
} from './domain/note';
export type {
    Note,
    NoteBlock,
    NoteBulletBlock,
    NoteCheckBlock,
    NoteColor,
    NoteDividerBlock,
    NoteFolder,
    NoteFolderRow,
    NoteHeadingBlock,
    NoteNumberBlock,
    NoteRow,
    NoteSummary,
    NoteTextBlock
} from './domain/note';
export {
    PROJECT_DESCRIPTION_MAX_LENGTH,
    PROJECT_ICON_MAX_LENGTH,
    PROJECT_MAX_TAGS,
    PROJECT_TAG_LABEL_MAX_LENGTH,
    PROJECT_TITLE_MAX_LENGTH,
    PROJECT_VERSION_MAX_LENGTH,
    projectDraftSchema,
    projectIconSchema,
    projectSchema,
    projectSecurityTierSchema,
    projectStatusSchema,
    projectSummarySchema,
    projectTagKindSchema,
    projectTagSchema,
    projectVersionSourceSchema
} from './domain/project';
export type {
    Project,
    ProjectDraft,
    ProjectRow,
    ProjectSecurityTier,
    ProjectStatus,
    ProjectSummary,
    ProjectTag,
    ProjectTagKind,
    ProjectVersionSource
} from './domain/project';
export {
    PROJECT_CARD_DESCRIPTION_MAX_LENGTH,
    PROJECT_CARD_TITLE_MAX_LENGTH,
    PROJECT_CHECKLIST_LABEL_MAX_LENGTH,
    PROJECT_COLUMN_NAME_MAX_LENGTH,
    PROJECT_MAX_CHECKLIST_ITEMS,
    PROJECT_MAX_COLUMNS,
    PROJECT_PRIORITIES,
    projectCardDraftSchema,
    projectCardSchema,
    projectChecklistItemSchema,
    projectColumnSchema,
    projectPrioritySchema
} from './domain/projectBoard';
export type {
    ProjectCard,
    ProjectCardDraft,
    ProjectCardRow,
    ProjectChecklistItem,
    ProjectColumn,
    ProjectColumnRow,
    ProjectPriority
} from './domain/projectBoard';
export {
    PROJECT_MESSAGE_MAX_LENGTH,
    PROJECT_MESSAGE_PAGE_SIZE,
    projectMessageSchema
} from './domain/projectChat';
export type { ProjectMessage, ProjectMessageRow } from './domain/projectChat';
export {
    PROJECT_MILESTONE_DESCRIPTION_MAX_LENGTH,
    PROJECT_MILESTONE_NAME_MAX_LENGTH,
    projectCardDepSchema,
    projectMilestoneDraftSchema,
    projectMilestoneSchema
} from './domain/projectPlan';
export type {
    ProjectCardDep,
    ProjectCardDepRow,
    ProjectMilestone,
    ProjectMilestoneDraft,
    ProjectMilestoneRow
} from './domain/projectPlan';
export {
    PROJECT_EVENT_LABEL_MAX_LENGTH,
    PROJECT_EVENT_PAGE_SIZE,
    projectEventKindSchema,
    projectEventRefSchema,
    projectEventSchema
} from './domain/projectHistory';
export {
    GIT_CREDENTIAL_LABEL_MAX_LENGTH,
    GIT_GRAPH_SHA_LEN,
    GIT_CREDENTIAL_SECRET_MAX_LENGTH,
    GIT_REPO_NAME_MAX_LENGTH,
    GIT_REPO_OWNER_MAX_LENGTH,
    gitBranchSchema,
    gitCommitAuthorSchema,
    gitCommitDetailSchema,
    gitCommitCursorSchema,
    gitCommitPointsSchema,
    gitCommitSchema,
    gitCredentialSchema,
    gitDiffFileSchema,
    gitDiffStatusSchema,
    gitProviderSchema,
    gitPullRequestSchema,
    gitPullStateSchema,
    gitReleaseSchema,
    gitRepoCandidateSchema,
    gitRepoSchema,
    gitRepoSyncStateSchema,
    gitRepoUsageSchema,
    gitSyncStatusSchema
} from './domain/git';
export {
    PROJECT_DEPLOY_DESCRIPTION_MAX_LENGTH,
    PROJECT_DEPLOY_TITLE_MAX_LENGTH,
    deployCandidateSchema,
    deployStatusSchema,
    deployTargetKindSchema,
    projectDeployTargetSchema,
    projectDeploymentSchema
} from './domain/projectDeploy';
export {
    DATABASE_ALERT_MESSAGE_MAX_LENGTH,
    DATABASE_ALERT_NAME_MAX_LENGTH,
    DATABASE_HOST_MAX_LENGTH,
    DATABASE_NAME_MAX_LENGTH,
    DATABASE_SECRET_MAX_LENGTH,
    DATABASE_SQL_MAX_LENGTH,
    DATABASE_USER_MAX_LENGTH,
    databaseAccessKindSchema,
    databaseAccessSchema,
    databaseAlertSchema,
    databaseCellSchema,
    databaseColumnSchema,
    databaseCombinatorSchema,
    databaseComparatorSchema,
    databaseConditionSchema,
    databaseEngineSchema,
    databaseExecutionSchema,
    databaseExportFormatSchema,
    databaseFilterOperatorSchema,
    databaseFilterSchema,
    databaseForeignKeySchema,
    databaseIdRangeSchema,
    databaseIndexSchema,
    databaseProbeSchema,
    databaseRowsSchema,
    databaseSchema,
    databaseSortSchema,
    databaseSshAuthSchema,
    databaseStatusSchema,
    databaseStructureSchema,
    databaseTableSchema,
    databaseUsageSchema
} from './domain/database';
export type {
    Database,
    DatabaseAccess,
    DatabaseAccessKind,
    DatabaseAlert,
    DatabaseAlertRow,
    DatabaseCell,
    DatabaseColumn,
    DatabaseCombinator,
    DatabaseComparator,
    DatabaseCondition,
    DatabaseEngine,
    DatabaseExecution,
    DatabaseExportFormat,
    DatabaseFilter,
    DatabaseFilterOperator,
    DatabaseForeignKey,
    DatabaseIdRange,
    DatabaseIndex,
    DatabaseProbe,
    DatabaseRow,
    DatabaseRows,
    DatabaseSort,
    DatabaseSshAuth,
    DatabaseStatus,
    DatabaseStructure,
    DatabaseTable,
    DatabaseUsage,
    ProjectDatabaseLinkRow
} from './domain/database';
export {
    AUDIENCE_BATCH_MAX,
    AUDIENCE_BREAKDOWN_MAX,
    AUDIENCE_DIMENSIONS,
    AUDIENCE_FUNNEL_MAX_STEPS,
    AUDIENCE_FUNNEL_NAME_MAX_LENGTH,
    AUDIENCE_LABEL_MAX_LENGTH,
    AUDIENCE_MAX_FUNNELS,
    AUDIENCE_MAX_ORIGINS,
    AUDIENCE_ORIGIN_MAX_LENGTH,
    AUDIENCE_PUBLIC_KEY_LENGTH,
    AUDIENCE_RETENTION_DEFAULT_DAYS,
    AUDIENCE_RETENTION_MAX_DAYS,
    AUDIENCE_RETENTION_MIN_DAYS,
    AUDIENCE_SESSION_GAP_SECONDS,
    AUDIENCE_SITE_DESCRIPTION_MAX_LENGTH,
    AUDIENCE_SITE_NAME_MAX_LENGTH,
    AUDIENCE_VISITOR_ID_MAX_LENGTH,
    audienceActivityCellSchema,
    audienceActivitySchema,
    audienceBreakdownItemSchema,
    audienceDimensionSchema,
    audienceEventInputSchema,
    audienceFunnelSchema,
    audienceFunnelStepDraftSchema,
    audienceFunnelStepKindSchema,
    audienceFunnelStepSchema,
    audienceIngestSchema,
    audienceLiveSchema,
    audienceMetricsSchema,
    audienceOverviewSchema,
    audiencePlatformSchema,
    audiencePointSchema,
    audienceRangeSchema,
    audienceResolutionSchema,
    audienceSiteSchema,
    audienceUsageSchema,
    audienceVisitorModeSchema
} from './domain/audience';
export type {
    AudienceActivity,
    AudienceActivityCell,
    AudienceBreakdownItem,
    AudienceDailyRow,
    AudienceDimension,
    AudienceEventInput,
    AudienceEventRow,
    AudienceFunnel,
    AudienceFunnelRow,
    AudienceFunnelStep,
    AudienceFunnelStepDraft,
    AudienceFunnelStepKind,
    AudienceFunnelStepRow,
    AudienceIngestBody,
    AudienceLabelRow,
    AudienceLive,
    AudienceMetrics,
    AudienceOverview,
    AudiencePlatform,
    AudiencePoint,
    AudienceRange,
    AudienceResolution,
    AudienceSessionRow,
    AudienceSite,
    AudienceSiteRow,
    AudienceUsage,
    AudienceVisitorMode,
    ProjectAudienceLinkRow
} from './domain/audience';
export { myTaskSchema, projectLinkCountsSchema } from './domain/projectLink';
export type { MyTask, ProjectLinkCounts, ProjectUptimeLinkRow } from './domain/projectLink';
export type {
    DeployCandidate,
    DeployStatus,
    DeployTargetKind,
    ProjectDeployTarget,
    ProjectDeployTargetRow,
    ProjectDeployment,
    ProjectDeploymentRow
} from './domain/projectDeploy';
export type {
    GitBranch,
    GitBranchRow,
    GitCommit,
    GitCommitAuthor,
    GitCommitAuthorRow,
    GitCommitDetail,
    GitCommitCursor,
    GitCommitPoints,
    GitCommitRow,
    GitCredential,
    GitCredentialRow,
    GitDiffFile,
    GitDiffStatus,
    GitProvider,
    GitPullRequest,
    GitPullRequestRow,
    GitPullState,
    GitRelease,
    GitReleaseRow,
    GitRepo,
    GitRepoCandidate,
    GitRepoRow,
    GitRepoSyncState,
    GitRepoUsage,
    GitSyncStatus,
    ProjectRepoLinkRow
} from './domain/git';
export type {
    ProjectEvent,
    ProjectEventKind,
    ProjectEventRef,
    ProjectEventRow
} from './domain/projectHistory';
export {
    UPTIME_INTERVAL_MAX,
    UPTIME_INTERVAL_MIN,
    UPTIME_KEYWORD_MAX_LENGTH,
    UPTIME_NAME_MAX_LENGTH,
    UPTIME_THRESHOLD_MAX,
    UPTIME_TIMEOUT_MAX,
    UPTIME_TIMEOUT_MIN,
    UPTIME_URL_MAX_LENGTH,
    uptimeCheckSchema,
    uptimeCheckStatsSchema,
    uptimeIncidentSchema,
    uptimeMethodSchema,
    uptimePointSchema,
    uptimeRangeSchema,
    uptimeResolutionSchema,
    uptimeRetentionSchema,
    uptimeServiceSchema,
    uptimeSettingsSchema,
    uptimeStatusSchema
} from './domain/uptime';
export type {
    UptimeCheck,
    UptimeCheckRow,
    UptimeCheckStats,
    UptimeDayRow,
    UptimeIncident,
    UptimeIncidentRow,
    UptimeMethod,
    UptimePoint,
    UptimeRange,
    UptimeResolution,
    UptimeService,
    UptimeServiceRow,
    UptimeSettings,
    UptimeSettingsRow,
    UptimeStatus
} from './domain/uptime';
export {
    MAIL_DISPLAY_NAME_MAX_LENGTH,
    MAIL_EMAIL_MAX_LENGTH,
    MAIL_HOST_MAX_LENGTH,
    MAIL_MESSAGE_PAGE_SIZE,
    MAIL_SEARCH_QUERY_MAX_LENGTH,
    MAIL_SNIPPET_MAX_LENGTH,
    MAIL_SUBJECT_MAX_LENGTH,
    MAIL_SYNC_INTERVAL_DEFAULT_MINUTES,
    MAIL_SYNC_INTERVAL_MAX_MINUTES,
    MAIL_SYNC_INTERVAL_MIN_MINUTES,
    mailAccountDraftSchema,
    mailAccountEditSchema,
    mailAccountSchema,
    mailAccountStatusSchema,
    mailAddressSchema,
    mailAttachmentSchema,
    mailAuthMethodSchema,
    mailBodyRenderModeSchema,
    mailFlagsSchema,
    mailFolderSchema,
    mailFolderSpecialUseSchema,
    mailHeaderSchema,
    mailLinkWarningReasonSchema,
    mailMessageCursorSchema,
    mailMessageSchema,
    mailMessageSummarySchema,
    mailOAuthProviderSchema,
    mailProxyKindSchema,
    mailProxySchema,
    mailSecurityTierSchema,
    mailSettingsSchema,
    mailSuspiciousLinkSchema
} from './domain/mail';
export type {
    MailAccount,
    MailAccountDraft,
    MailAccountEdit,
    MailAccountRow,
    MailAccountStatus,
    MailAddress,
    MailAttachment,
    MailAuthMethod,
    MailBodyRenderMode,
    MailFlags,
    MailFolder,
    MailFolderRow,
    MailFolderSpecialUse,
    MailHeader,
    MailLinkWarningReason,
    MailMessage,
    MailMessageCursor,
    MailMessageRow,
    MailMessageSummary,
    MailOAuthProvider,
    MailProxy,
    MailProxyKind,
    MailSecurityTier,
    MailSettings,
    MailSettingsRow,
    MailSuspiciousLink
} from './domain/mail';
export { userRoleSchema } from './domain/role';
export type { UserRole } from './domain/role';
export {
    homeFeatureIdSchema,
    homeLayoutSchema,
    homeSectionKindSchema,
    homeSectionSchema,
    homeTopbarWidgetIdSchema,
    shortcutItemSchema,
    shortcutPreviewSchema,
    shortcutTemplateSchema,
    SHORTCUT_URL_MAX_LENGTH
} from './domain/home';
export type {
    HomeFeatureId,
    HomeLayout,
    HomeSection,
    HomeSectionKind,
    HomeTopbarWidgetId,
    ShortcutItem,
    ShortcutPreview,
    ShortcutTemplate
} from './domain/home';
export {
    liveCursorKindSchema,
    liveCursorSchema,
    livePathGate,
    livePathSchema,
    livePathSegmentSchema,
    livePeerSchema,
    liveTopicSchema,
    segmentKind,
    segmentValue,
    TOPIC_FEATURE
} from './domain/live';
export type {
    LiveCursor,
    LiveCursorKind,
    LivePath,
    LivePathGate,
    LivePeer,
    LiveTopic
} from './domain/live';
export {
    LIVE_CHANGED_EVENT,
    LIVE_CURSOR_COMMAND,
    LIVE_CURSORS_EVENT,
    LIVE_PEERS_EVENT,
    LIVE_TYPERS_EVENT,
    LIVE_TYPING_COMMAND,
    liveChangedPushSchema,
    liveCommands,
    liveCursorFrameSchema,
    liveCursorsPushSchema,
    liveHere,
    livePeersPushSchema,
    liveTypersPushSchema,
    liveTypingFrameSchema
} from './features/live';
export type {
    LiveChangedPush,
    LiveCursorFrame,
    LiveCursorsPush,
    LivePeersPush,
    LiveTypersPush,
    LiveTypingFrame
} from './features/live';
export {
    defaultUserColor,
    minimalUserSchema,
    USER_COLORS,
    userColorSchema,
    userSchema,
    userSecuritySchema,
    userSettingFlagSchema,
    userStatusSchema
} from './domain/user';
export type {
    MinimalUser,
    User,
    UserColor,
    UserRow,
    UserSecurity,
    UserSettingFlag,
    UserStatus
} from './domain/user';
export { secrecyStatusSchema, secrecyWrapModeSchema } from './domain/secrecy';
export type { SecrecyStatus, SecrecyWrapMode, UserSecretKeyRow } from './domain/secrecy';
export { workspaceKindSchema, workspaceSchema } from './domain/workspace';
export {
    featureAccessSchema,
    WORKSPACE_CAPABILITIES,
    WORKSPACE_FEATURE_IDS,
    WORKSPACE_ROLE_NAME_MAX,
    workspaceCapabilitySchema,
    workspaceFeatureGrantSchema,
    workspaceFeatureIdSchema,
    workspacePermissionsSchema,
    workspaceRoleSchema
} from './domain/workspaceRole';
export type {
    FeatureAccess,
    WorkspaceCapability,
    WorkspaceFeatureGrant,
    WorkspaceFeatureId,
    WorkspacePermissions,
    WorkspaceRole,
    WorkspaceRoleRow
} from './domain/workspaceRole';
export type {
    Workspace,
    WorkspaceKind,
    WorkspaceMemberRow,
    WorkspaceRow
} from './domain/workspace';
export {
    DEFAULT_METRIC_INTERVAL_SECONDS,
    DEFAULT_PROCESS_CAPTURE,
    DEFAULT_RETENTION_DAYS,
    devicePlatformSchema,
    deviceSchema,
    deviceStatusSchema
} from './domain/device';
export type {
    Device,
    DevicePlatform,
    DeviceRow,
    DeviceStatus,
    DeviceWorkspaceRow
} from './domain/device';
export { packageManagerIdSchema, packageManagerSchema } from './domain/packages';
export type { PackageManager, PackageManagerId } from './domain/packages';
export {
    agentInfoSchema,
    agentServiceScopeSchema,
    AUTH_LOGIN_LIMIT,
    AUTH_SOURCE_LIMIT,
    authLoginSchema,
    authSourceSchema,
    authWindowSchema,
    cpuInfoSchema,
    deviceHardwareSchema,
    deviceReportSchema,
    deviceSecuritySchema,
    integrityReportSchema,
    mandatoryAccessControlSchema,
    netInterfaceKindSchema,
    netInterfaceSchema,
    openPortSchema,
    PERSISTENCE_ENTRY_LIMIT,
    persistenceEntrySchema,
    processCaptureSchema,
    processKindSchema,
    processSampleSchema,
    reportDiskSchema,
    reportProcessSchema,
    tcpConnectionSchema
} from './domain/report';
export type {
    AgentInfo,
    AgentServiceScope,
    AuthLogin,
    AuthSource,
    AuthWindow,
    CpuInfo,
    DeviceHardware,
    DeviceReport,
    DeviceSecurity,
    IntegrityReport,
    MandatoryAccessControl,
    NetInterface,
    NetInterfaceKind,
    OpenPort,
    PersistenceEntry,
    ProcessCapture,
    ProcessKind,
    ProcessSample,
    ReportDisk,
    ReportProcess,
    TcpConnection
} from './domain/report';
export {
    allowEntrySchema,
    allowScopeSchema,
    BASELINE_RULES,
    baselineAttrsSchema,
    baselineEntrySchema,
    baselineKindSchema,
    DEFAULT_SENTINEL_FINDING_RETENTION_DAYS,
    DEFAULT_SENTINEL_INTEGRITY_MINUTES,
    DEFAULT_SENTINEL_LEARNING_DAYS,
    devicePostureSchema,
    deviceSentinelStateSchema,
    evidenceItemSchema,
    findingSchema,
    findingSeveritySchema,
    findingStateSchema,
    postureCheckSchema,
    postureStatusSchema,
    ruleProbeSchema,
    SENTINEL_INTEGRITY_MINUTES_MAX,
    SENTINEL_INTEGRITY_MINUTES_MIN,
    SENTINEL_LEARNING_DAYS_MAX,
    SENTINEL_LEARNING_DAYS_MIN,
    SENTINEL_NOTIFY_FROM,
    SENTINEL_RULES,
    sentinelConfigSchema,
    sentinelRuleIdSchema,
    SEVERITY_BY_RANK,
    SEVERITY_RANK,
    severityCountsSchema
} from './domain/sentinel';
export type {
    AllowEntry,
    AllowScope,
    BaselineAttrs,
    BaselineEntry,
    BaselineKind,
    DevicePosture,
    DeviceSentinelState,
    EvidenceItem,
    Finding,
    FindingSeverity,
    FindingState,
    PostureCheck,
    PostureStatus,
    RuleProbe,
    SentinelConfig,
    SentinelRuleId,
    SentinelRuleMeta,
    SeverityCounts
} from './domain/sentinel';
export {
    detectTarget,
    OSINT_HISTORY_PAGE_MAX,
    OSINT_PROBE_LABELS,
    OSINT_PROBES_BY_KIND,
    OSINT_PROVIDER_META,
    OSINT_QUERY_MAX_LENGTH,
    OSINT_RAW_MAX_LENGTH,
    OSINT_SLOW_PROBES,
    osintFieldSchema,
    osintHistoryEntrySchema,
    osintLinkSchema,
    osintProbeIdSchema,
    osintProbeResultSchema,
    osintProbeStatusSchema,
    osintProviderSchema,
    osintProviderStatusSchema,
    osintScoreSchema,
    osintTagSchema,
    osintTargetKindSchema,
    osintTargetSchema,
    osintToneSchema
} from './domain/osint';
export type {
    OsintField,
    OsintHistoryEntry,
    OsintLink,
    OsintLookupRow,
    OsintProbeId,
    OsintProbeResult,
    OsintProbeStatus,
    OsintProvider,
    OsintProviderKeyRow,
    OsintProviderStatus,
    OsintScore,
    OsintTag,
    OsintTarget,
    OsintTargetKind,
    OsintTone
} from './domain/osint';
export { notificationFeatureSchema, notificationSettingsSchema } from './domain/notifications';
export type {
    NotificationFeature,
    NotificationSettings,
    NotificationSettingsRow
} from './domain/notifications';
export { presenceEventSchema } from './domain/presence';
export type { PresenceEvent, PresenceRow } from './domain/presence';
export {
    metricSeriesPointSchema,
    metricSnapshotSchema,
    metricsBatchSchema,
    metricsResolutionSchema
} from './domain/metrics';
export type {
    MetricRow,
    MetricSeriesPoint,
    MetricSnapshot,
    MetricsBatch,
    MetricsResolution
} from './domain/metrics';
export { twoFactorSetupSchema, twoFactorStatusSchema } from './domain/twoFactor';
export type {
    BackupCodeRow,
    TwoFactorRow,
    TwoFactorSetup,
    TwoFactorStatus
} from './domain/twoFactor';
export {
    weatherConditionSchema,
    weatherDaySchema,
    weatherFormatSchema,
    weatherHourSchema,
    weatherLocationSchema,
    weatherProviderSchema,
    weatherReportSchema
} from './domain/weather';
export type {
    WeatherCondition,
    WeatherDay,
    WeatherFormat,
    WeatherHour,
    WeatherLocation,
    WeatherLocationRow,
    WeatherProvider,
    WeatherProviderKeyRow,
    WeatherReport
} from './domain/weather';

// Features
export {
    passwordAdd,
    passwordCommands,
    passwordCount,
    passwordDelete,
    passwordEdit,
    passwordGet,
    passwordList,
    passwordUnlock
} from './features/password';
export {
    folderAdd,
    folderDelete,
    folderList,
    folderRename,
    folderReorder,
    noteAdd,
    noteArchive,
    noteCommands,
    noteCount,
    noteDelete,
    noteEdit,
    noteGet,
    noteList,
    noteReorder,
    noteRestore
} from './features/note';
export {
    projectAdd,
    projectArchive,
    projectBoard,
    projectCardAdd,
    projectCardArchive,
    projectCardMove,
    projectCardRestore,
    projectCardUpdate,
    projectColumnAdd,
    projectColumnRemove,
    projectColumnReorder,
    projectColumnUpdate,
    projectCommands,
    projectCardSetMilestone,
    projectDepAdd,
    projectDepRemove,
    projectDeployCandidates,
    projectDeployGet,
    projectDeployLink,
    projectDeployList,
    projectDeployTrigger,
    projectDeployUnlink,
    projectMyTasks,
    projectLinkCounts,
    projectAudienceLink,
    projectAudienceList,
    projectAudienceUnlink,
    projectDatabaseLink,
    projectDatabaseList,
    projectDatabaseUnlink,
    projectUptimeLink,
    projectUptimeList,
    projectUptimeUnlink,
    projectEventList,
    projectMarkRead,
    projectMessageEdit,
    projectMessageList,
    projectMessageSend,
    projectMilestoneAdd,
    projectMilestoneRemove,
    projectMilestoneSetReached,
    projectMilestoneUpdate,
    projectPlan,
    projectRepoList,
    projectRepoLink,
    projectRepoUnlink,
    projectCount,
    projectGet,
    projectList,
    projectReorder,
    projectRestore,
    projectSetSecurityTier,
    projectSetStatus,
    projectSetVersion,
    projectUpdate
} from './features/project';
export {
    gitAuthorMap,
    gitBranchList,
    gitCommands,
    gitCommitDetail,
    gitCommitGraph,
    gitCommitList,
    gitCount,
    gitCredentialAdd,
    gitCredentialList,
    gitCredentialRemove,
    gitCredentialUpdate,
    gitPullRequestList,
    gitReleaseList,
    gitRepoAdd,
    gitRepoCandidates,
    gitRepoGet,
    gitRepoList,
    gitRepoRemove,
    gitRepoReorder,
    gitRepoResync,
    gitRepoSyncNow,
    gitRepoSyncStatus,
    gitRepoUpdate,
    gitSyncStatuses
} from './features/git';
export {
    databaseAdd,
    databaseAlertAdd,
    databaseAlertList,
    databaseAlertRemove,
    databaseAlertTest,
    databaseAlertUpdate,
    databaseCommands,
    databaseCount,
    databaseGet,
    databaseInspect,
    databaseList,
    databaseQuery,
    databaseRemove,
    databaseReorder,
    databaseExecute,
    databaseExport,
    databaseRowDelete,
    databaseRowInsert,
    databaseRowUpdate,
    databaseTableList,
    databaseTableRows,
    databaseTableStructure,
    databaseTest,
    databaseTestDraft,
    databaseUpdate
} from './features/database';
export {
    audienceActivity,
    audienceBreakdown,
    audienceCommands,
    audienceCount,
    audienceFunnelAdd,
    audienceFunnelList,
    audienceFunnelRemove,
    audienceFunnelUpdate,
    audienceGet,
    audienceList,
    audienceLive,
    audienceOverview,
    audienceReorder,
    audienceSiteAdd,
    audienceSiteRemove,
    audienceSiteRotateKey,
    audienceSiteUpdate
} from './features/audience';

export { homeCommands, homeSetLayout, homeShortcutPreview } from './features/home';
export { featureCommandRegistry, featureCommands } from './features/registry';
export type {
    CommandInput,
    CommandOutput,
    FeatureCommandDescriptor,
    FeatureCommandName
} from './features/registry';
export {
    adminCommands,
    adminDeleteUser,
    adminInviteCreate,
    adminInviteList,
    adminInviteRevoke,
    adminInviteSchema,
    adminSetUserRole,
    adminSetUserStatus,
    adminUserList,
    adminUserSchema
} from './features/admin';
export type { AdminInvite, AdminUser } from './features/admin';
export {
    workspaceActivate,
    workspaceAdd,
    workspaceCommands,
    workspaceDelete,
    workspaceEnableSharedKey,
    workspaceLeave,
    workspaceRemoveMember,
    workspaceAddMember,
    workspaceAssignRole,
    workspaceRename,
    workspaceRoleCreate,
    workspaceRoleDelete,
    workspaceRoleList,
    workspaceRoleSetDefault,
    workspaceRoleUpdate,
    workspaceSetFavorite,
    workspaceSharedKeyStatus
} from './features/workspace';
export {
    AVATAR_MAX_LENGTH,
    THEME_IMAGE_MAX_LENGTH,
    THEME_SLOT_COUNT,
    THEME_SLOT_IMAGE_MAX_LENGTH,
    themeStateSchema,
    userCommands,
    userSetAvatar,
    userSetColor,
    userSetSetting,
    userSetTheme
} from './features/user';
export type { ThemeStateDTO } from './features/user';
export {
    deviceCancelDelete,
    deviceCommands,
    deviceConfirm,
    deviceDelete,
    deviceDropPrivileges,
    deviceElevate,
    deviceForceDelete,
    deviceList,
    deviceListPackages,
    deviceAgentLifecycle,
    devicePower,
    deviceReactivate,
    deviceRename,
    deviceReorder,
    deviceRequestDelete,
    deviceRevoke,
    deviceSetAutostart,
    deviceSetConfig,
    deviceSetWorkspaces,
    deviceShareTargetSchema,
    deviceUpdateAgent,
    deviceUpgradePackages,
    deviceWorkspaceList
} from './features/device';
export type { DeviceShareTarget } from './features/device';
export { deviceLogCommands, deviceLogQuery, deviceLogSources } from './features/deviceLogs';
export {
    deviceFilesAnalyze,
    deviceFilesCommands,
    deviceFilesDownload,
    deviceFilesList,
    deviceFilesMutate,
    deviceFilesSearch,
    deviceFilesUpload
} from './features/deviceFiles';
export {
    cloudSyncAddExclusion,
    cloudSyncAttachDevice,
    cloudSyncBrowse,
    cloudSyncClearVersions,
    cloudSyncCommands,
    cloudSyncCreateShare,
    cloudSyncDeleteShare,
    cloudSyncDeleteVersion,
    cloudSyncDeleteVersions,
    cloudSyncDetachDevice,
    cloudSyncDownloadFile,
    cloudSyncDownloadVersion,
    cloudSyncListEvents,
    cloudSyncListShares,
    cloudSyncListVersions,
    cloudSyncPauseDevice,
    cloudSyncPauseShare,
    cloudSyncRemoveExclusion,
    cloudSyncRestoreVersion,
    cloudSyncResumeDevice,
    cloudSyncResumeShare,
    cloudSyncSubscribe,
    cloudSyncSyncNow,
    cloudSyncUnsubscribe,
    cloudSyncUpdateShare,
    cloudSyncValidatePath
} from './features/cloudSync';
export {
    deviceTerminalCommands,
    deviceTermClose,
    deviceTermInput,
    deviceTermOpen,
    deviceTermResize,
    terminalUser
} from './features/deviceTerminal';
export {
    metricsAvailability,
    metricsCommands,
    metricsDeleteSnapshots,
    metricsPresence,
    metricsProcessesAt,
    metricsQuery,
    metricsRefresh,
    metricsSetSnapshotsPinned,
    metricsSnapshots,
    metricsStorage,
    metricsSubscribe,
    metricsUnsubscribe
} from './features/metrics';
export {
    weatherAdd,
    weatherCommands,
    weatherGet,
    weatherList,
    weatherRemove,
    weatherReorder,
    weatherSetKey,
    weatherSetPrimary,
    weatherUpdate
} from './features/weather';
export {
    osintCommands,
    osintHistory,
    osintHistoryClear,
    osintHistoryRemove,
    osintKeyList,
    osintLookup,
    osintProbe,
    osintSetKey
} from './features/osint';
export {
    SENTINEL_PAGE_MAX,
    sentinelAcknowledge,
    sentinelAllowlist,
    sentinelBaseline,
    sentinelCommands,
    sentinelCount,
    sentinelFindings,
    sentinelGetSettings,
    sentinelOverview,
    sentinelPosture,
    sentinelRemoveAllow,
    sentinelReopen,
    sentinelResetBaseline,
    sentinelScanNow,
    sentinelSetConfig,
    sentinelSetSettings,
    sentinelTestNotification
} from './features/sentinel';
export {
    uptimeAdd,
    uptimeCheckNow,
    uptimeChecks,
    uptimeCheckStats,
    uptimeCommands,
    uptimeCount,
    uptimeGetSettings,
    uptimeHistory,
    uptimeIncidents,
    uptimeList,
    uptimeRemove,
    uptimeReorder,
    uptimeSetEnabled,
    uptimeSetSettings,
    uptimeTestNotification,
    uptimeUpdate
} from './features/uptime';
export {
    twoFactorCommands,
    twoFactorDisable,
    twoFactorEnable,
    twoFactorGetStatus,
    twoFactorRegenBackup,
    twoFactorSetup
} from './features/twoFactor';
export {
    secrecyCommands,
    secrecyDisable,
    secrecyEnable,
    secrecyHold,
    secrecyLock,
    secrecyRecover,
    secrecySetReauth,
    secrecyStatus,
    secrecyTouch,
    secrecyUnlock
} from './features/secrecy';
export {
    LOGS_PAGE_DEFAULT,
    LOGS_PAGE_MAX,
    logFilterSchema,
    logsCommands,
    logsFacetSchema,
    logsFacetUserSchema,
    logsFacets,
    logsList
} from './features/logs';
export type { LogFilter } from './features/logs';
export {
    mailAccountAdd,
    mailAccountCount,
    mailAccountDelete,
    mailAccountList,
    mailAccountReorder,
    mailAccountSetEnabled,
    mailAccountSetProfile,
    mailAccountTestConnection,
    mailAccountUpdate,
    mailAttachmentDownload,
    mailAttachmentScan,
    mailCommands,
    mailFolderBackfill,
    mailFolderList,
    mailFolderReorder,
    mailFolderReset,
    mailFolderSync,
    mailGetSettings,
    mailMessageDelete,
    mailMessageGet,
    mailMessageList,
    mailMessageMove,
    mailMessageSearch,
    mailMessageSetFlags,
    mailOAuthStart,
    mailSend,
    mailSetSettings
} from './features/mail';

// HTTP
export {
    changePasswordRequestSchema,
    changePasswordResponseSchema,
    loginRequestSchema,
    loginResponseSchema,
    meResponseSchema,
    refreshResponseSchema,
    registerRequestSchema,
    sessionBundleSchema,
    twoFactorChallengeRequestSchema
} from './http/auth';
export type {
    ChangePasswordRequest,
    ChangePasswordResponse,
    LoginRequest,
    LoginResponse,
    MeResponse,
    RefreshResponse,
    RegisterRequest,
    SessionBundle,
    TwoFactorChallengeRequest
} from './http/auth';
export {
    AGENT_TARGETS,
    agentManifestSchema,
    agentManifestTargetSchema,
    agentTargetSchema,
    agentTargetsResponseSchema,
    agentTargetStatusSchema,
    enrollDeviceRequestSchema,
    enrollDeviceResponseSchema,
    LINK_CODE_TTL_MAX_SECONDS,
    linkCodeRequestSchema,
    linkCodeResponseSchema,
    linkCodesListResponseSchema,
    linkCodeUpdateSchema
} from './http/device';
export type {
    AgentManifest,
    AgentManifestTarget,
    AgentOs,
    AgentTarget,
    AgentTargetMeta,
    AgentTargetsResponse,
    AgentTargetStatus,
    EnrollDeviceRequest,
    EnrollDeviceResponse,
    LinkCodeRequest,
    LinkCodeResponse,
    LinkCodesListResponse,
    LinkCodeUpdate
} from './http/device';
export { bootTaskSchema, bootTaskStateSchema, serverStatusSchema } from './http/status';
export type { BootTask, BootTaskState, ServerStatus } from './http/status';

// Utils
export { compareVersions, isNewerVersion } from './utils/version';
